"""frecuencia de series

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-25 18:02:19.746251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import portafolio.data.tipos


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frecuencia', sa.Enum('DIARIA', 'MENSUAL', name='frecuencia', native_enum=False, length=20), server_default='DIARIA', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serie', schema=None) as batch_op:
        batch_op.drop_column('frecuencia')

    # ### end Alembic commands ###
