"""modelo inicial

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 15:41:11.453091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import portafolio.data.tipos


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parametro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('valor', portafolio.data.tipos.DecimalExacto(precision=24, escala=10), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parametro')),
    sa.UniqueConstraint('nombre', 'vigente_desde', name=op.f('uq_parametro_nombre_vigente_desde'))
    )
    op.create_table('serie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('INDICADOR', 'PRECIO', 'VALOR_UNIDAD', name='tiposerie', native_enum=False, length=20), nullable=False),
    sa.Column('fuente', sa.String(length=100), nullable=True),
    sa.Column('unidad', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_serie')),
    sa.UniqueConstraint('codigo', name=op.f('uq_serie_codigo'))
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('email', name=op.f('uq_usuario_email'))
    )
    op.create_table('portafolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], name=op.f('fk_portafolio_usuario_id_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portafolio')),
    sa.UniqueConstraint('id', 'usuario_id', name=op.f('uq_portafolio_id_usuario_id')),
    sa.UniqueConstraint('usuario_id', 'nombre', name=op.f('uq_portafolio_usuario_id_nombre'))
    )
    with op.batch_alter_table('portafolio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portafolio_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('valor_serie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('valor', portafolio.data.tipos.DecimalExacto(precision=24, escala=10), nullable=False),
    sa.ForeignKeyConstraint(['serie_id'], ['serie.id'], name=op.f('fk_valor_serie_serie_id_serie'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_valor_serie')),
    sa.UniqueConstraint('serie_id', 'fecha', name=op.f('uq_valor_serie_serie_id_fecha'))
    )
    with op.batch_alter_table('valor_serie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valor_serie_serie_id'), ['serie_id'], unique=False)

    op.create_table('instrumento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('portafolio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('CUENTA', 'CDT', 'FIC', 'ACCION', 'ETF', 'BONO', 'OTRO', name='tipoinstrumento', native_enum=False, length=20), nullable=False),
    sa.Column('emisor', sa.String(length=200), nullable=True),
    sa.Column('moneda', sa.String(length=3), nullable=False),
    sa.Column('serie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['portafolio_id', 'usuario_id'], ['portafolio.id', 'portafolio.usuario_id'], name=op.f('fk_instrumento_portafolio_id_portafolio')),
    sa.ForeignKeyConstraint(['serie_id'], ['serie.id'], name=op.f('fk_instrumento_serie_id_serie')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instrumento')),
    sa.UniqueConstraint('id', 'portafolio_id', 'usuario_id', name=op.f('uq_instrumento_id_portafolio_id_usuario_id')),
    sa.UniqueConstraint('portafolio_id', 'nombre', name=op.f('uq_instrumento_portafolio_id_nombre'))
    )
    with op.batch_alter_table('instrumento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instrumento_portafolio_id'), ['portafolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_instrumento_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('objetivo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('portafolio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('monto_meta', portafolio.data.tipos.DecimalExacto(precision=20, escala=6), nullable=False),
    sa.Column('fecha_meta', sa.Date(), nullable=False),
    sa.Column('en_pesos_reales', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['portafolio_id', 'usuario_id'], ['portafolio.id', 'portafolio.usuario_id'], name=op.f('fk_objetivo_portafolio_id_portafolio')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_objetivo'))
    )
    with op.batch_alter_table('objetivo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_objetivo_portafolio_id'), ['portafolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_objetivo_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('movimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('portafolio_id', sa.Integer(), nullable=False),
    sa.Column('instrumento_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('APORTE', 'RETIRO', 'COMPRA', 'VENTA', 'DIVIDENDO', 'INTERES', 'IMPUESTO', 'COMISION', name='tipomovimiento', native_enum=False, length=20), nullable=False),
    sa.Column('monto', portafolio.data.tipos.DecimalExacto(precision=20, escala=6), nullable=False),
    sa.Column('nota', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instrumento_id', 'portafolio_id', 'usuario_id'], ['instrumento.id', 'instrumento.portafolio_id', 'instrumento.usuario_id'], name=op.f('fk_movimiento_instrumento_id_instrumento')),
    sa.ForeignKeyConstraint(['portafolio_id', 'usuario_id'], ['portafolio.id', 'portafolio.usuario_id'], name=op.f('fk_movimiento_portafolio_id_portafolio')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimiento'))
    )
    with op.batch_alter_table('movimiento', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimiento_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimiento_instrumento_id'), ['instrumento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimiento_portafolio_id'), ['portafolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimiento_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('valoracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('portafolio_id', sa.Integer(), nullable=False),
    sa.Column('instrumento_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('valor', portafolio.data.tipos.DecimalExacto(precision=20, escala=6), nullable=False),
    sa.ForeignKeyConstraint(['instrumento_id', 'portafolio_id', 'usuario_id'], ['instrumento.id', 'instrumento.portafolio_id', 'instrumento.usuario_id'], name=op.f('fk_valoracion_instrumento_id_instrumento')),
    sa.ForeignKeyConstraint(['portafolio_id', 'usuario_id'], ['portafolio.id', 'portafolio.usuario_id'], name=op.f('fk_valoracion_portafolio_id_portafolio')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_valoracion')),
    sa.UniqueConstraint('instrumento_id', 'fecha', name=op.f('uq_valoracion_instrumento_id_fecha'))
    )
    with op.batch_alter_table('valoracion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valoracion_instrumento_id'), ['instrumento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_valoracion_portafolio_id'), ['portafolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_valoracion_usuario_id'), ['usuario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('valoracion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valoracion_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_valoracion_portafolio_id'))
        batch_op.drop_index(batch_op.f('ix_valoracion_instrumento_id'))

    op.drop_table('valoracion')
    with op.batch_alter_table('movimiento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimiento_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_movimiento_portafolio_id'))
        batch_op.drop_index(batch_op.f('ix_movimiento_instrumento_id'))
        batch_op.drop_index(batch_op.f('ix_movimiento_fecha'))

    op.drop_table('movimiento')
    with op.batch_alter_table('objetivo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_objetivo_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_objetivo_portafolio_id'))

    op.drop_table('objetivo')
    with op.batch_alter_table('instrumento', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instrumento_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_instrumento_portafolio_id'))

    op.drop_table('instrumento')
    with op.batch_alter_table('valor_serie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valor_serie_serie_id'))

    op.drop_table('valor_serie')
    with op.batch_alter_table('portafolio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portafolio_usuario_id'))

    op.drop_table('portafolio')
    op.drop_table('usuario')
    op.drop_table('serie')
    op.drop_table('parametro')
    # ### end Alembic commands ###
