"""usuarios multiusuario

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-25 18:31:55.024768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import portafolio.data.tipos


revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emisor', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('sujeto', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('es_administrador', sa.Boolean(), server_default=sa.false(), nullable=False))
        batch_op.add_column(sa.Column('autorizacion_datos_en', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('version_politica', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_usuario_emisor_sujeto'), ['emisor', 'sujeto'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_usuario_emisor_sujeto'), type_='unique')
        batch_op.drop_column('version_politica')
        batch_op.drop_column('autorizacion_datos_en')
        batch_op.drop_column('es_administrador')
        batch_op.drop_column('sujeto')
        batch_op.drop_column('emisor')

    # ### end Alembic commands ###
