"""cdt y gmf

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-25 17:55:56.720112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import portafolio.data.tipos


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('condicion_cdt',
    sa.Column('instrumento_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('portafolio_id', sa.Integer(), nullable=False),
    sa.Column('capital', portafolio.data.tipos.DecimalExacto(precision=20, escala=6), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('tasa', portafolio.data.tipos.DecimalExacto(precision=24, escala=10), nullable=False),
    sa.Column('tipo_tasa', sa.Enum('EFECTIVA_ANUAL', 'NOMINAL', name='tipotasa', native_enum=False, length=20), nullable=False),
    sa.Column('periodicidad', sa.Enum('MENSUAL', 'BIMESTRAL', 'TRIMESTRAL', 'SEMESTRAL', 'ANUAL', 'AL_VENCIMIENTO', name='periodicidad', native_enum=False, length=20), nullable=False),
    sa.Column('modalidad', sa.Enum('VENCIDA', 'ANTICIPADA', name='modalidad', native_enum=False, length=20), nullable=False),
    sa.Column('base_dias', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instrumento_id', 'portafolio_id', 'usuario_id'], ['instrumento.id', 'instrumento.portafolio_id', 'instrumento.usuario_id'], name=op.f('fk_condicion_cdt_instrumento_id_instrumento')),
    sa.ForeignKeyConstraint(['portafolio_id', 'usuario_id'], ['portafolio.id', 'portafolio.usuario_id'], name=op.f('fk_condicion_cdt_portafolio_id_portafolio')),
    sa.PrimaryKeyConstraint('instrumento_id', name=op.f('pk_condicion_cdt'))
    )
    with op.batch_alter_table('condicion_cdt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_condicion_cdt_portafolio_id'), ['portafolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_condicion_cdt_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('instrumento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exenta_gmf', sa.Boolean(), server_default=sa.false(), nullable=False))

    with op.batch_alter_table('movimiento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clave_generacion', sa.String(length=60), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_movimiento_instrumento_id_clave_generacion'), ['instrumento_id', 'clave_generacion'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimiento', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_movimiento_instrumento_id_clave_generacion'), type_='unique')
        batch_op.drop_column('clave_generacion')

    with op.batch_alter_table('instrumento', schema=None) as batch_op:
        batch_op.drop_column('exenta_gmf')

    with op.batch_alter_table('condicion_cdt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_condicion_cdt_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_condicion_cdt_portafolio_id'))

    op.drop_table('condicion_cdt')
    # ### end Alembic commands ###
